# Generated by Django 4.2.6 on 2023-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_ord_value',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=7, verbose_name='Minimum Order Value'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
