# Generated by Django 4.2.6 on 2023-10-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_expiry_date_coupon_min_ord_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='ec_coupons',
        ),
    ]
