# Generated by Django 4.2.6 on 2023-10-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default='3c1364e7-2089-4afc-8b8c-5f5a56f9dfb0', editable=False, primary_key=True, serialize=False),
        ),
    ]
