# Generated by Django 4.2.6 on 2023-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default='7f426570-75b1-44f5-8a61-f94fa079c9b6', editable=False, primary_key=True, serialize=False),
        ),
    ]
