# Generated by Django 4.2.6 on 2023-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default='e95a475c-e540-409c-a746-802a31e31088', editable=False, primary_key=True, serialize=False),
        ),
    ]
