# Generated by Django 4.2.6 on 2023-10-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_shipping_price_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default='a8e96338-315e-497c-8589-0681ae446642', editable=False, primary_key=True, serialize=False),
        ),
    ]
