# Generated by Django 4.2.6 on 2023-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_alter_cart_id_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default='cd3e926a-d33b-404e-a165-4b250096dade', editable=False, primary_key=True, serialize=False),
        ),
    ]
