# Generated by Django 4.2.6 on 2023-10-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=10)),
                ('pin_code', models.CharField(max_length=6)),
                ('locality', models.CharField(max_length=75)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=50, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='utilities.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='utilities.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Addresses',
                'db_table': 'ec_user_addresses',
            },
        ),
    ]
