# Generated by Django 4.2.6 on 2023-10-14 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuseraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseraddress',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('(?!([\\d])\x01{9})[6789]\\d{9}$', 'Number invalid!')]),
        ),
        migrations.AlterField(
            model_name='customuseraddress',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('(?!([\\d])\x01{9})[6789]\\d{9}$', 'Number invalid!')]),
        ),
        migrations.AlterField(
            model_name='customuseraddress',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Pincode invalid!')]),
        ),
        migrations.AlterField(
            model_name='customuserdetail',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('(?!([\\d])\x01{9})[6789]\\d{9}$', 'Number invalid!')]),
        ),
    ]
