# Generated by Django 4.2.6 on 2023-10-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
