# Generated by Django 4.2.6 on 2023-10-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_processed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SHIPPED', 'SHIPPED'), ('RETURNED', 'RETURNED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=25),
        ),
    ]
